# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-dask-manager-binding
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: airflow-dask-executor
  namespace: airflow
roleRef:
  kind: ClusterRole
  name: dask-cluster-manager
  apiGroup: rbac.authorization.k8s.io
