# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-dask-manager-binding
  namespace: dask-service-clusters
subjects:
- kind: ServiceAccount
  name: airflow-dask-executor
  namespace: airflow
roleRef:
  kind: Role
  name: dask-cluster-manager
  apiGroup: rbac.authorization.k8s.io
